### ISSUE TITLE
Mailchimp account management

### ISSUE THREAD

**Issue by desi** [bridgefoundry/operations#123]
Can you login to your mailchimp account with [sarah@bridgefoundry.org](mailto:sarah@bridgefoundry.org) and add me to all Bridge Foundry projects you have so that I can manage them?

**Comment by ultrasaurus** [comment]
Removed Ilen with the intent to add Desi, but that didn't allow me to add another user.  To add one we need to resubscribe.  Let's chat about what you wanna do!

**Comment by desi** [comment]
I mostly want to get the account shut down if we aren't using it because Nola is still getting notification as primary on the project which she'd like to stop getting. I can pair with you on this next time to see where we are with it.

**Comment by ultrasaurus** [comment]
That's surprising since she's not listed as a user.  Ping me on slack to coordinate a time, maybe you can find out where she's included, tho I suspect we may have accidentally created multiple accounts.  (Perhaps have her forward one of the notifications?)
