### ISSUE TITLE
Establish a fund link doesn't seem to go to the right place

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/operations#13]
In the [README.md](https://github.com/bridgefoundry/operations/blob/aeb70c1a9d1605222a14ae6d78926aaaac665943/README.md), under the "How to" section it says:
* establish a fund as a new Bridge or as a new Chapter of a Bridge

but the link goes to sponsorship, which doesn't seem right.  I can't find the page for this... does it exist somewhere or do we need to write that content?

**Comment by dianaluepke** [comment]
Non-issue now that School Factory documentation is archived.
