### ISSUE TITLE
Update name of Roles folder

### ISSUE THREAD

**Issue by dianaluepke** [bridgefoundry/operations#33]
We need to un-capitalize the Roles folder name. (Created before I knew about capitalization mattering on the markdown pages. If I shouldn't be using capitalization for issues either, let me know!)

Could someone either a) fix it for me or b) teach me how? I think I _might_ be able to manage it from the command line but I probably need supervision. I figured out how to do it directly from Github with another folder, but it involved updating it for each separate document and I figure there must be a faster way!

Thanks!
Diana

**Comment by paulproteus** [comment]
This works easily on Linux, but is difficult on Mac OS and Windows.

See e.g. this reference https://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive

I'll address this in an upcoming pull request (that I think @ultrasaurus might merge) which adds mkdocs configuration to this project.

**Comment by dianaluepke** [comment]
Thanks, Asheesh! Closing issue.
