### ISSUE TITLE
need index for corporate-docs/policy

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/operations#88]
https://operations.bridgefoundry.org/corporate-docs/ has link to: https://operations.bridgefoundry.org/corporate-docs/policy which is a 404

It would be nice to have an autogenerated index, for this directory in github: https://github.com/bridgefoundry/operations/tree/master/docs/corporate-docs/policy

**Comment by ultrasaurus** [comment]
@paulproteus do you have any suggestions on how to do this?

**Comment by mxie** [comment]
After reading through mkdocs' [config docs](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation) it looks like the tool _will_ still generate the page -- it just won't be linked in the navigation if we have a custom order defined in the `mkdocs.yml` file.

However, if we _do_ go with the GitHub Actions option for deployment, we could potentially write a script that'd list everything in that directory and then append it to the `mkdocs.yml` file. This is all assuming that we'd always have the "Corporate Docs" section last though.

Curious to hear about your thoughts, @paulproteus!
