### ISSUE TITLE
Broken link from bridgefoundry.org website to https://operations.bridgefoundry.org/corporate-docs/

### ISSUE THREAD

**Issue by cczona** [bridgefoundry/operations#97]
The link to Corporate Policies https://operations.bridgefoundry.org/corporate-docs/policy 404s

**Comment by mxie** [comment]
Thanks for reporting this @cczona! Transferring this issue over to the operations repo for tracking.

**Comment by ultrasaurus** [comment]
@mxie if that text is on the website, it's a website bug, right?  or do you think there should be a re-direct for an old link?

**Comment by ultrasaurus** [comment]
Maybe this is the same as: https://github.com/bridgefoundry/operations/issues/88 ?
